import {
  faSliders,
  faChartColumn,
  faMoneyCheckPen,
  faClipboardQuestion,
  faRightToBracket,
  faEnvelopeCircleCheck,
} from '@fortawesome/pro-light-svg-icons';

import { faGripLines } from '@fortawesome/pro-thin-svg-icons';

import {
  faPlus,
  faBolt,
  faToggleOn,
  faDrumstick,
  faBowlRice,
  faPeanuts,
} from '@fortawesome/sharp-solid-svg-icons';

import {
  faXmark as faXmarkSolid,
  faCheck,
  faRoute,
  faArrowLeft,
  faListCheck,
  faMagnifyingGlass,
  faArrowRotateRight,
} from '@fortawesome/free-solid-svg-icons';
import {
  faGoogle,
  faTwitter,
  faFacebookF,
  faInstagram,
  faWhatsappSquare,
} from '@fortawesome/free-brands-svg-icons';

import {
  faSpinnerThird,
  faUser,
  faCircleNotch,
  faMessageExclamation,
  faBars,
  faRotateBack,
  faPotFood,
  faSalad,
  faDumbbell,
  faCommentsQuestionCheck,
  faShirt,
  faTelescope,
  faHeartPulse,
  faPersonDollyEmpty,
  faArrowRight,
  faPaperPlane,
} from '@fortawesome/pro-solid-svg-icons';
import { faHouseTree } from '@fortawesome/pro-regular-svg-icons';

export const FontAwesomeicons = [
  faBolt,
  faPlus,
  faToggleOn,
  faUser,
  faBars,
  faRoute,
  faSalad,
  faCheck,
  faShirt,
  faGoogle,
  faArrowLeft,
  // faFilePen,
  faPeanuts,
  faPotFood,
  faSliders,
  faTwitter,
  faDumbbell,
  faBowlRice,
  faChartColumn,
  faGripLines,
  faDrumstick,
  faTelescope,
  faFacebookF,
  faHouseTree,
  faInstagram,
  // faCaretRight,
  faPaperPlane,
  faArrowRight,
  faListCheck,
  faXmarkSolid,
  faRotateBack,
  faArrowRotateRight,
  faHeartPulse,
  faMoneyCheckPen,
  faCircleNotch,
  faSpinnerThird,
  faRightToBracket,
  faMagnifyingGlass,
  faWhatsappSquare,
  faPersonDollyEmpty,
  faClipboardQuestion,
  faMessageExclamation,
  faEnvelopeCircleCheck,
  faCommentsQuestionCheck,
];
