name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.ADRIAN_BADILLA_ADMIN_ACCESS_TOKEN_NXCLOUD }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Enable Nx Cloud task distribution early
      - name: Start Nx Cloud task distribution
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-small-js" --stop-agents-after="e2e-ci"

      - name: Enable Corepack for Yarn v2+ PnP
        run: corepack enable

      # Cache Yarn Plug’n’Play artifacts for faster installs (Option 3)
      - name: Cache Yarn PnP
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .pnp.*
          key: ${{ runner.os }}-yarn-pnp-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-pnp-

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Install Cypress binary
      - name: Install Cypress
        run: npx cypress install

      - name: Set NX shas
        uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by changes.
      # To record logs to Nx Cloud, prepend commands with "nx-cloud record --"
      # Uncomment and adjust the following lines as needed:
      # - name: Record a custom Nx Cloud log
      #   run: npx nx-cloud record -- echo "Hello, Nx Cloud!"
      # - name: Run affected tasks
      #   run: npx nx affected -t lint test build e2e
